"""add dob and make phone unique

Revision ID: 2d9b7729715b
Revises: df71e531d24a
Create Date: 2026-05-17 06:12:36.886058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9b7729715b'
down_revision = 'df71e531d24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
